create table ROLE (
                      id integer generated by default as identity,
                      role_name varchar(255),
                      primary key (id)
);

create table USER(
                        id integer generated by default as identity,
                        username varchar(255),
                        password varchar(255),
                        primary key (id)
);

create table USER_ROLES (
                            user_id bigint not null,
                            roles_id integer not null
);